package janela;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import script.*;

public class JAN_Principal extends javax.swing.JFrame {

    private static String[] musicas;
    public static Connect connect;
    private String ip;
    private static Tocador tocador;
    private static int indexMusic;
    private static String music;
    
    public JAN_Principal() {
        connect = null;
        initComponents();
        ArquivaMusic.criarPasta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLmusicas = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        JTip = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTcaminho = new javax.swing.JTextField();
        JBconectar = new javax.swing.JButton();
        JLabelx1 = new javax.swing.JLabel();
        JLabelx2 = new javax.swing.JLabel();
        JLabelx3 = new javax.swing.JLabel();
        JTstatus = new javax.swing.JLabel();
        JBnewCaminho = new javax.swing.JButton();
        JControle = new javax.swing.JLabel();
        JCplayer = new javax.swing.JLabel();
        JCanterior = new javax.swing.JLabel();
        JCproximo = new javax.swing.JLabel();
        JCstop = new javax.swing.JLabel();
        JCpause = new javax.swing.JLabel();
        JLtimer = new javax.swing.JLabel();
        JLmusicStatus = new javax.swing.JLabel();
        JTaleatorio = new javax.swing.JLabel();
        JTrepeteMusic = new javax.swing.JLabel();
        JBdisconnect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Musicas Stream");

        jLmusicas.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLmusicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLmusicasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jLmusicas);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel1.setText("IP:");

        JTip.setText("192.168.1.126");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel2.setText("Caminho:");

        JTcaminho.setText("D:/documentos/musicas/Musicas Caique/The Beatles/Melhores");

        JBconectar.setText("Conectar");
        JBconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBconectarActionPerformed(evt);
            }
        });

        JLabelx1.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        JLabelx1.setText("Titulo:");

        JLabelx2.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        JLabelx2.setText("Artista:");

        JLabelx3.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        JLabelx3.setText("Album:");

        JTstatus.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        JTstatus.setText("Status: Desconectado");

        JBnewCaminho.setText("Novo Caminho");

        JControle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reduzido.png"))); // NOI18N

        JCplayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCplayerMouseClicked(evt);
            }
        });

        JCanterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCanteriorMouseClicked(evt);
            }
        });

        JCproximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCproximoMouseClicked(evt);
            }
        });

        JCstop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCstopMouseClicked(evt);
            }
        });

        JCpause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCpauseMouseClicked(evt);
            }
        });

        JLtimer.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        JLtimer.setText("00:00");

        JLmusicStatus.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        JLmusicStatus.setText("Musica Status");

        JTaleatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/aleatorio.png"))); // NOI18N
        JTaleatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTaleatorioMouseClicked(evt);
            }
        });

        JTrepeteMusic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/repete.png"))); // NOI18N
        JTrepeteMusic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTrepeteMusicMouseClicked(evt);
            }
        });

        JBdisconnect.setText("Disconnect");
        JBdisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBdisconnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(12, 12, 12)
                                .addComponent(JTip, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(177, 177, 177)
                                .addComponent(JBconectar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)
                                .addComponent(JTcaminho, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(321, 321, 321)
                                .addComponent(JBnewCaminho))
                            .addComponent(JLabelx2)
                            .addComponent(JLabelx3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTstatus)
                                    .addComponent(JLabelx1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JBdisconnect)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(JLtimer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(JTaleatorio)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCstop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCanterior, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JControle)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JCpause, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JCplayer, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(JCproximo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(JTrepeteMusic))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JLmusicStatus))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel1))
                            .addComponent(JBconectar)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(JTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel2))
                            .addComponent(JTcaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(JBnewCaminho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTstatus)
                            .addComponent(JBdisconnect))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLabelx1)
                        .addGap(18, 18, 18)
                        .addComponent(JLabelx2)
                        .addGap(18, 18, 18)
                        .addComponent(JLabelx3)
                        .addGap(51, 51, 51)
                        .addComponent(JLtimer)
                        .addGap(26, 26, 26)
                        .addComponent(JLmusicStatus)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCplayer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCproximo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCanterior, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JControle)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTaleatorio)
                                    .addComponent(JTrepeteMusic))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JCpause, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JCstop, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLmusicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLmusicasMouseClicked
        JList list = (JList)evt.getSource();
        indexMusic = list.locationToIndex(evt.getPoint());
        
        if(evt.getClickCount() == 2){
            music = musicas[indexMusic];
            System.out.println("Musica: "+music);
            if(music == null) return;
            if(tocador != null)
                if(!tocador.isStopTotal()) tocador.stop();
            tocador = AutoPlay.tocarNovaMusic(tocador, connect, music);
        }
    }//GEN-LAST:event_jLmusicasMouseClicked

    private void JBconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBconectarActionPerformed
        ip = JTip.getText();
        System.out.println(ip);
        connect = new Connect(ip);
        if(connect.isConnectado()){
            JBconectar.setEnabled(false);
            JTstatus.setText("Conectado");
            String caminho = JTcaminho.getText();
            String nomes[] = connect.enviarCaminho(caminho);
            setLista(nomes);
            
        }
    }//GEN-LAST:event_JBconectarActionPerformed

    private void JCplayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCplayerMouseClicked
        if(tocador != null)
            if(tocador.isStopTotal() == false) tocador.resume();
            else tocador.play();
        else JLmusicStatus.setText("Selecione uma musica");
    }//GEN-LAST:event_JCplayerMouseClicked

    private void JCanteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCanteriorMouseClicked
        if(tocador != null)
        if((indexMusic - 1) > 0){
            tocador.stop();
            String str[] = {musicas[indexMusic - 2], musicas[indexMusic - 1], musicas[indexMusic]};
            indexMusic--;
            AutoPlay.novaFila(str);
            if(!ArquivaMusic.verificaArquivoExiste(musicas[indexMusic]))
                try {
                    connect.solicitaMusic(musicas[indexMusic]);
                } catch (IOException ex) {
                    Logger.getLogger(JAN_Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            tocador = new Tocador(musicas[indexMusic]);
            tocador.play();
            jLmusicas.setSelectedIndex(indexMusic);
        }
        else JLmusicStatus.setText("Selecione uma musica");
    }//GEN-LAST:event_JCanteriorMouseClicked

    private void JCproximoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCproximoMouseClicked
        try { proximaMusica(); } catch (IOException ex) {
            Logger.getLogger(JAN_Principal.class.getName()).log(Level.SEVERE, null, ex); }
    }//GEN-LAST:event_JCproximoMouseClicked

    private void JCstopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCstopMouseClicked
        if(tocador != null) tocador.stop();
        else JLmusicStatus.setText("Selecione uma musica");
    }//GEN-LAST:event_JCstopMouseClicked

    private void JCpauseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCpauseMouseClicked
        if(tocador != null) tocador.pause();
        else JLmusicStatus.setText("Selecione uma musica");
    }//GEN-LAST:event_JCpauseMouseClicked

    private void JTaleatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTaleatorioMouseClicked
        musicas = AutoPlay.Aleatorio(musicas);
        setLista(musicas);
    }//GEN-LAST:event_JTaleatorioMouseClicked

    private void JTrepeteMusicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTrepeteMusicMouseClicked
        if(AutoPlay.isRepeti()) AutoPlay.desativaRepeticao();
        else AutoPlay.ativaRepeticao();
    }//GEN-LAST:event_JTrepeteMusicMouseClicked

    private void JBdisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBdisconnectActionPerformed
        
    }//GEN-LAST:event_JBdisconnectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAN_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAN_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAN_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAN_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JAN_Principal().setVisible(true);
            }
        });
    }
    
    private void setLista(String[] nomes){
        DefaultListModel newListModel = new DefaultListModel();
        musicas = nomes;
        for (String nome : nomes) {
           newListModel.addElement(nome);
        }
        jLmusicas.setModel(newListModel);
    }
    
    public static boolean hasProximo(){
        return !(indexMusic == (musicas.length - 1));
    }
    
    public static void proximaMusica() throws IOException{
        System.out.println("JAN proxima musica");
        if(hasProximo()) {
            indexMusic++;
            music = musicas[indexMusic];
            tocador = AutoPlay.tocarNovaMusic(tocador, connect, music);
        }else if(indexMusic > -1) {
            indexMusic = 0;
            music = musicas[indexMusic];
            tocador = AutoPlay.tocarNovaMusic(tocador, connect, music);
        }
        if(indexMusic >= 0 && indexMusic < musicas.length) jLmusicas.setSelectedIndex(indexMusic);
        downloadProxima();
    }
    
    private static void downloadProxima() throws IOException{
        String music;
        if(hasProximo()) music = musicas[indexMusic + 1];
        else music = musicas[0];
        new Thread(){
            @Override            
            public void run() {        
                if(!ArquivaMusic.verificaArquivoExiste(music)){
                    System.out.println("Baixando musica");
                    try {
                        connect.solicitaMusic(music);
                    } catch (IOException ex) {
                        Logger.getLogger(JAN_Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else
                    System.out.println("Não baixou, musica já existe");
            }
        }.start();
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBconectar;
    private javax.swing.JButton JBdisconnect;
    private javax.swing.JButton JBnewCaminho;
    private javax.swing.JLabel JCanterior;
    private javax.swing.JLabel JControle;
    private javax.swing.JLabel JCpause;
    private javax.swing.JLabel JCplayer;
    private javax.swing.JLabel JCproximo;
    private javax.swing.JLabel JCstop;
    private javax.swing.JLabel JLabelx1;
    private javax.swing.JLabel JLabelx2;
    private javax.swing.JLabel JLabelx3;
    public static javax.swing.JLabel JLmusicStatus;
    public static javax.swing.JLabel JLtimer;
    private javax.swing.JLabel JTaleatorio;
    private javax.swing.JTextField JTcaminho;
    private javax.swing.JTextField JTip;
    private javax.swing.JLabel JTrepeteMusic;
    private javax.swing.JLabel JTstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private static javax.swing.JList<String> jLmusicas;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
