package janela;

import script.Campeonato;
import script.ConnectSQL;
import script.Time;

/**
 *
 * @author caique
 */
public class Tabela extends javax.swing.JFrame {

    Campeonato campeonato;
    
    public Tabela(Campeonato campeonato) {
        campeonato.getTimes().clear();
        initComponents();
        this.campeonato = campeonato;
        JLcamp.setText(campeonato.getNome());
        getDadosBD();
        iniciaValoresTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLcamp = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BRodada = new javax.swing.JButton();
        BRodada1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLcamp.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        JLcamp.setText("Tabela");

        jTable1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Pos", "Time", "Pts", "J", "V", "E", "D", "GP", "GC", "SG"
            }
        ));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        BRodada.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        BRodada.setText("Rodada");
        BRodada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRodadaActionPerformed(evt);
            }
        });

        BRodada1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        BRodada1.setText("Cancelar");
        BRodada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRodada1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BRodada)
                            .addComponent(BRodada1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(JLcamp)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLcamp)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(BRodada)
                        .addGap(72, 72, 72)
                        .addComponent(BRodada1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BRodadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRodadaActionPerformed
        // RODADA
        dispose();
        Rodada janela = new Rodada(campeonato);
        janela.setVisible(true);
        janela.setLocation(300, 300);
        janela.setResizable(false);
    }//GEN-LAST:event_BRodadaActionPerformed

    private void BRodada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRodada1ActionPerformed
        // CANCELAR
        dispose();
        Principal janela = new Principal();
        janela.setVisible(true);
        janela.setLocation(300, 300);
        janela.setResizable(false);
    }//GEN-LAST:event_BRodada1ActionPerformed

    public void getDadosBD(){
        ConnectSQL sql = new ConnectSQL();
        sql.getINFOR_TIME(campeonato);
    }
    
    public void iniciaValoresTabela(){
        for(int i=0; i<campeonato.getTimes().size(); i++){
            Time time = campeonato.getTimes().get(i);
            jTable1.setValueAt(i+1, i, 0);
            jTable1.setValueAt(time.getNome(), i, 1);
            jTable1.setValueAt(time.getPontos(), i, 2);
            jTable1.setValueAt(time.getJogos(), i, 3);
            jTable1.setValueAt(time.getVitorias(), i, 4);
            jTable1.setValueAt(time.getEmpates(), i, 5);
            jTable1.setValueAt(time.getDerrotas(), i, 6);
            jTable1.setValueAt(time.getGP(), i, 7);
            jTable1.setValueAt(time.getGC(), i, 8);
            jTable1.setValueAt(time.getSaldo(), i, 9);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BRodada;
    private javax.swing.JButton BRodada1;
    private javax.swing.JLabel JLcamp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
